version: '3.8'

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true" # ⚠️ desative em produção
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080" # Dashboard Traefik
    networks:
      - controle_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  db:
    image: mysql:8.0
    container_name: controle_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - controle_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: controle_material-backend:latest
    container_name: controle_backend
    restart: always
    env_file:
      - .env
      - ./backend/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.estoque.ti.wasion.com.br`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=3001"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - controle_net

  frontend:
    image: controle_material-frontend:latest
    container_name: controle_frontend
    restart: always
    environment:
      - VITE_API_URL=http://api.estoque.ti.wasion.com.br
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`estoque.ti.wasion.com.br`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - controle_net

volumes:
  db_data:

networks:
  controle_net:
    driver: bridge
